version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0

workflows:
  publishing:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          context: codurance
          checkout: true
          orb-path: src/@orb.yml
          orb-name: codurance/aws-deploy-to-beanstalk
          requires:
            - orb-tools/lint
      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          context: codurance
          checkout: true
          orb-name: codurance/aws-deploy-to-beanstalk
          add-pr-comment: false
          publish-version-tag: false
          fail-if-semver-not-indicated: false
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
